Create Base Archive Template on src/render_engine/render_engine_templ…
kjaymiller/render_engine pull request #226
Opened 2023-07-18 02:53 UTC by viktoriussuwandi

fixed #104 

Hi [kjaymiller](https://github.com/kjaymiller),
I'm trying to add couple of recommended lines on [src/render_engine/render_engine_templates/base.html](https://github.com/kjaymiller/render_engine/blob/main/src/render_engine/render_engine_templates/base.html).

But not sure the file location, please check it out

2023-07-18 03:40 UTC, kjaymiller commented
base isn't where it should go but I'm working on some things that may make this need some more thought... We can leave it open for now but may not wind up being added due to the issue being not relevant.

2023-07-18 04:06 UTC, viktoriussuwandi commented
> base isn't where it should go but I'm working on some things that may make this need some more thought... We can leave it open for now but may not wind up being added due to the issue being not relevant.

ok @kjaymiller , I'm open to help

2023-07-19 12:24 UTC, kjaymiller requested changes

2023-07-19 12:24 UTC, kjaymiller commented on src/render_engine/render_engine_templates/base.html
The added content in this file should be in a new file perhaps `archive.html`.

you'd want to extend `base.html`.


```html
{% extends 'base.html' %}
{% block content %}
                <h1>{{collection_title}}</h1>
                {% for page in pages %}
                <div><a href="{{page.url_for}}">{{page}}</a></div>
                {% endfor %}
{% endblock %}
```

2023-07-19 12:24 UTC, kjaymiller commented on src/render_engine/render_engine_templates/base.html
@viktoriussuwandi to clarify you'd create this in a new file `src/render_engine/render_engine_templates/archive.html`

2023-07-19 13:26 UTC, viktoriussuwandi commented on src/render_engine/render_engine_templates/base.html
@kjaymiller , 
1. I try put these lines on the new file src/render_engine/render_engine_templates/archive.html
2. I try to restore [src/render_engine/render_engine_templates/base.html](https://github.com/kjaymiller/render_engine/blob/main/src/render_engine/render_engine_templates/base.html).

Please check it out

2023-07-19 14:05 UTC, kjaymiller approved these changes

2023-07-19 14:06 UTC, merged

2023-11-21 19:02 UTC, kjaymiller commented
@all-contributors please add @viktoriussuwandi for Code